### ISSUE TITLE
A Dislike button, but without karma tracking. Maybe BuzzFeed-style emotes (which I think are fun, ymmv)

### ISSUE THREAD

**Issue by vai** [MLTSHP/mltshp_migration#25]

**Comment by Down10** [comment]
This was my suggestion. I was thinking that if we have a Like button, why not a Dislike button? I know this is not at present in the current form of Mlkshk, and that Facebook famously does not have one, but Andre's past, er, file-sharing site did. 

Another alternative would be to offer BuzzFeed-style reactions (heart, broken heart, "cute", "eww", "lol", "wtf", etc.) which can be fun or obnoxious, depending on your point of view. I think it offers more variety in response and can be a way of filtering posts to a theme that suits your desires.

Just some ideas.

**Comment by patrickt** [comment]
Moved to the mltshp repo.
