### ISSUE TITLE
Link after I uploaded picture via bookmarklet

### ISSUE THREAD

**Issue by borked** [MLTSHP/mltshp_migration#44]
Almost always after I upload a pic via the bookmarklet I want to check out if everything went okay, if I have new messages etc. So I click on the MLKSH / MLTSHP logo on the top left of the 'your image has been saved' page. (http://mlkshk.com/tools/p)

BUT THE LOGO HAS NO LINK! 

It drives me nuts, and I asked @andre a couple of times, to no avail.

Seems like an easy fix/enhancement.

**Comment by iLama** [comment]
This seems like a reasonable and simple to implement feature request.

**Comment by patrickt** [comment]
Moved to the mltshp repo.
