### ISSUE TITLE
Create a user import process

### ISSUE THREAD

**Issue by vosechu** [MLTSHP/mltshp_migration#46]
Import process possibilities

1. Import all the users/comments/preferences/images, but exclude user content until they opt-in
> Pros: We have a copy of all the comments/images so people can sign up a year from now and find all their images repopulated.
    Cons: Lots of spam images/comments, expensive queries, possible weirdness in comment threads where one comment says "user not migrated" or something
    Questions: What does a comment look like for a user that hasn't opted-in?

2. Import all the users/comments/preferences/images
>   Pros: Hella easy
    Cons: Possibly illegal/immoral depending on how you read the privacy policy

3. Import data when a user signs up
>   Pros: No spam, every user on the site is certainly engaged
    Cons: Import process could take _hours or days_ depending on how many images need to be ported over, need to store a copy of all images/comments just in case someone signs up later, super complicated queries to find the _just_ the rows that need to be imported, then off of that all the images that we need to download. 
    Questions: What does the site look like for the user while the import is running? How do we let them know when it's done? What happens if it fails? What happens if they don't opt-in for a year?

**Comment by bradchoate** [comment]
For the sake of expediency, I say we relaunch with an empty database. We can add a migration form after relaunch, and a process around that to make sure MLTSHP user "foo" doesn't try to migrate MLKSHK user "foo" that may not actually be their account-- some kind of verification should be in place there. We're getting a copy of the data, so we can import their shakes, their images afterward. We should limit the window for offering that to some reasonable period, but probably no more than 1 year.

**Comment by vai** [comment]
Seconding 'just get it running fresh' - changes and extensions still need implementation, testing, and we're not all familiar yet with even running it as is. Starting off with the app working, in production, and beginning to see use will be the first win. We should however, start thinking about how the process of opt-in import will work, so we can prototype, and consider the edge cases.

I'm happy with the idea of unimported users just being displayed as @redacted ~redacted~ in comment threads, but will also suggest we allow users to choose whether to import anything, to import just their posts, their posts with their comments, and also optionally, the users'  own comments on other posts. Some community polling on what's expected/preferred here might be good too.

**Comment by vosechu** [comment]
I can commit to this.

We will pay for it later, but I think a blank site running closer to 4/1 is
better than a well oiled machine running closer to 4/15.

**Comment by ardgedee** [comment]
@vosechu @bradchoate Is this ticket resolved?

**Comment by bradchoate** [comment]
It is resolved. We went with option 3 in the end. Forgot about the ticket itself.
